##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-power-manager
    - autoconf-archive
    - clang
    - dbus-glib
    - file
    - gcc
    - git
    - itstool
    - libcanberra
    - libgnome-keyring
    - libnotify
    - make
    - mate-common
    - mate-panel
    - python
    - upower
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-power-manager
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libgcrypt20-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libnotify-dev
    - libtool-bin
    - libupower-glib-dev
    - libx11-dev
    - libxext-dev
    - libxml-parser-perl
    - libxrandr-dev
    - make
    - mate-common
    - pkg-config
    - xmlto
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-power-manager.git
    - autoconf-archive
    - cairo-devel
    - clang
    - clang-analyzer
    - cppcheck-htmlreport
    - dbus-glib-devel
    - desktop-file-utils
    - gcc
    - git
    - glib2-devel
    - gtk3-devel
    - libcanberra-devel
    - libgnome-keyring-devel
    - libnotify-devel
    - make
    - mate-common
    - mate-panel-devel
    - mesa-libGL-devel
    - pangox-compat-devel
    - polkit-devel
    - popt-devel
    - redhat-rpm-config
    - upower-devel

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libgcrypt20-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libnotify-dev
    - libtool-bin
    - libupower-glib-dev
    - libx11-dev
    - libxext-dev
    - libxml-parser-perl
    - libxrandr-dev
    - make
    - mate-common
    - pkg-config
    - xmlto
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security -Wredundant-decls"
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - '[ -f mate-common-1.23.3.tar.xz ] || curl -Ls -o mate-common-1.23.3.tar.xz http://pub.mate-desktop.org/releases/1.23/mate-common-1.23.3.tar.xz'
  - tar xf mate-common-1.23.3.tar.xz
  - cd mate-common-1.23.3
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./autogen.sh --without-keyring --enable-compile-warnings=maximum
  -     scan-build $CHECKERS ./configure --without-keyring --enable-compile-warnings=maximum
  - else
  -     ./autogen.sh --enable-compile-warnings=maximum
  -     scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - fi
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/${REPO_NAME}/raw/master/data/icons/16x16/apps/mate-power-manager.png
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-power-manager-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

